apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: ../mp4s
        containerPath: /mp4s
    extraPortMappings:
      - containerPort: 30080
        hostPort: 8080
        listenAddress: "127.0.0.1"
      - containerPort: 31935
        hostPort: 1935
        listenAddress: "127.0.0.1"
