apiVersion: v1
kind: Service
metadata:
  name: transcoder
spec:
  ports:
  - name: web
    nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 80
  - name: rtmp
    nodePort: 31935
    port: 1935
    protocol: TCP
    targetPort: 1935
  selector:
    app: nginx-render
  type: NodePort
