apiVersion: v1
kind: Service
metadata:
  name: video-on-demand
spec:
  ports:
  - name: web
    nodePort: 31000
    port: 80
    protocol: TCP
    targetPort: 80
  - name: rtmp
    nodePort: 31001
    port: 1935
    protocol: TCP
    targetPort: 1935
  selector:
    app: nginx-render
  type: NodePort
